(part "MF-RHS800-0"
    (packageRef "MFRHS8000")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-MF-RHS800-0")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/MF-RHS800-0?qs=mELouGlnn3db4Obe02aVdw%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "MF-RHS800-0")
    (property "Description" "PTC 8.0A 16V RADIAL LEADED HI-TEMP")
    (property "Datasheet_Link" "https://www.bourns.com/docs/Product-Datasheets/MF-RHS.pdf")
    (property "symbolName1" "MF-RHS800-0")
)
