(part "CDSOT23-T15C-Q"
    (packageRef "SOT95P230X117-3N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-CDSOT23-T15C-Q")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/CDSOT23-T15C-Q?qs=gZXFycFWdAPB6hWJxc%252Bycg%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "CDSOT23-T15C-Q")
    (property "Description" "ESD Suppressors / TVS Diodes TVS Diode 15V 500W BIDIR SOT23")
    (property "Datasheet_Link" "https://www.bourns.com/docs/product-datasheets/CDSOT23-TxxC-Q.pdf")
    (property "symbolName1" "CDSOT23-T15C-Q")
)
