(part "3588-15"
    (packageRef "358815")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "534-3588-15")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Keystone-Electronics/3588-15?qs=u16ybLDytRaSVK7r0YphMA%3D%3D")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "3588-15")
    (property "Description" "Fuse Holder 20 A 500V 1 Circuit Blade Surface Mount")
    (property "Datasheet_Link" "http://www.keystoneelectronics.net/ENG._DEPT/WEB_ORACLE/PDF/PDF%20CAT%20NO%20DRAWINGS/3000-3999/3588-15.PDF")
    (property "symbolName1" "3588-15")
)
