(part "SF-1206HHA800R-2"
    (packageRef "SF1206HHA800R2")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-SF-1206HHA800R-2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/SF-1206HHA800R-2?qs=Imq1NPwxi77tr2%2FYGnM5Ig%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "SF-1206HHA800R-2")
    (property "Description" "1206 high-current met-foil. 8A Auto")
    (property "Datasheet_Link" "https://www.bourns.com/docs/Product-Datasheets/SF-1206HHA-R.pdf")
    (property "symbolName1" "SF-1206HHA800R-2")
)
