(part "560020-1020"
    (packageRef "5600201020")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "MP1" (symbPinId 11) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 12) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-560020-1020")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/560020-1020?qs=c8NFF48pVsBr9szpbon2vA%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "560020-1020")
    (property "Description" "Headers & Wire Housings 2.0 W/B SMT ST10ckt EMBOSSED TP PKG")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/5600201020_sd.pdf")
    (property "symbolName1" "560020-1020")
)
