(part "B6B-XH-A_LF__SN_"
    (packageRef "SHDR6W64P0X250_1X6_1740X575X700P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "306-B6BXHALFSN")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/JST-Commercial/B6B-XH-ALFSN?qs=cdbOS8ANM9AKmMmofXbwlw%3D%3D")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "B6B-XH-A(LF)(SN)")
    (property "Description" "CONN HEADER VERT 6POS 2.5MM")
    (property "Datasheet_Link" "https://datasheet.lcsc.com/szlcsc/JST-Sales-America-B6B-XH-A-LF-SN_C144397.pdf")
    (property "symbolName1" "B6B-XH-A_LF__SN_")
)
